function Ticks () {
    if (hackbit.buttonState(DigitalPin.P1, false)) {
        for (let index = 0; index < 3; index++) {
            strip.showRainbow(1, 360)
            basic.pause(100)
            Strip2.showRainbow(1, 360)
            basic.pause(500)
            strip.showColor(neopixel.colors(NeoPixelColors.Black))
            basic.pause(100)
            Strip2.showColor(neopixel.colors(NeoPixelColors.Black))
            basic.pause(500)
        }
        strip.showColor(neopixel.colors(NeoPixelColors.Black))
    } else {
        basic.pause(200)
    }
}
let strip: neopixel.Strip = null
let Strip2: neopixel.Strip = null
Strip2 = neopixel.create(DigitalPin.P16, 30, NeoPixelMode.RGB)
strip = neopixel.create(DigitalPin.P2, 30, NeoPixelMode.RGB)
strip.showColor(neopixel.colors(NeoPixelColors.Black))
Strip2.showColor(neopixel.colors(NeoPixelColors.Black))
basic.forever(function () {
    for (let index = 0; index < 1e+101; index++) {
        strip.show()
        strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Blue))
        strip.setPixelColor(1, neopixel.colors(NeoPixelColors.Blue))
        strip.setPixelColor(2, neopixel.colors(NeoPixelColors.White))
        Ticks()
        strip.show()
        strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Black))
        strip.setPixelColor(2, neopixel.colors(NeoPixelColors.Blue))
        strip.setPixelColor(3, neopixel.colors(NeoPixelColors.White))
        Ticks()
        strip.show()
        strip.setPixelColor(1, neopixel.colors(NeoPixelColors.Black))
        strip.setPixelColor(3, neopixel.colors(NeoPixelColors.Blue))
        strip.setPixelColor(4, neopixel.colors(NeoPixelColors.White))
        Ticks()
        strip.show()
        strip.setPixelColor(2, neopixel.colors(NeoPixelColors.Black))
        strip.setPixelColor(4, neopixel.colors(NeoPixelColors.Blue))
        strip.setPixelColor(5, neopixel.colors(NeoPixelColors.White))
        Ticks()
        strip.show()
        strip.setPixelColor(3, neopixel.colors(NeoPixelColors.Black))
        strip.setPixelColor(5, neopixel.colors(NeoPixelColors.Blue))
        strip.setPixelColor(6, neopixel.colors(NeoPixelColors.White))
        Ticks()
        strip.show()
        strip.setPixelColor(4, neopixel.colors(NeoPixelColors.Black))
        strip.setPixelColor(6, neopixel.colors(NeoPixelColors.Blue))
        strip.setPixelColor(7, neopixel.colors(NeoPixelColors.White))
        Ticks()
        strip.show()
        strip.setPixelColor(5, neopixel.colors(NeoPixelColors.Black))
        strip.setPixelColor(7, neopixel.colors(NeoPixelColors.Blue))
        strip.setPixelColor(8, neopixel.colors(NeoPixelColors.White))
        Ticks()
        strip.show()
        strip.setPixelColor(6, neopixel.colors(NeoPixelColors.Black))
        strip.setPixelColor(8, neopixel.colors(NeoPixelColors.Blue))
        strip.setPixelColor(9, neopixel.colors(NeoPixelColors.White))
        Ticks()
        strip.show()
        strip.setPixelColor(7, neopixel.colors(NeoPixelColors.Black))
        strip.setPixelColor(9, neopixel.colors(NeoPixelColors.Blue))
        strip.setPixelColor(10, neopixel.colors(NeoPixelColors.White))
        Ticks()
        strip.show()
        strip.setPixelColor(8, neopixel.colors(NeoPixelColors.Black))
        strip.setPixelColor(10, neopixel.colors(NeoPixelColors.Blue))
        strip.setPixelColor(11, neopixel.colors(NeoPixelColors.White))
        Ticks()
        strip.show()
        strip.setPixelColor(9, neopixel.colors(NeoPixelColors.Black))
        strip.setPixelColor(11, neopixel.colors(NeoPixelColors.Blue))
        strip.setPixelColor(12, neopixel.colors(NeoPixelColors.White))
        Ticks()
        strip.show()
        strip.setPixelColor(10, neopixel.colors(NeoPixelColors.Black))
        strip.setPixelColor(12, neopixel.colors(NeoPixelColors.Blue))
        strip.setPixelColor(13, neopixel.colors(NeoPixelColors.White))
        Ticks()
        strip.show()
        strip.setPixelColor(11, neopixel.colors(NeoPixelColors.Black))
        strip.setPixelColor(13, neopixel.colors(NeoPixelColors.Blue))
        strip.setPixelColor(14, neopixel.colors(NeoPixelColors.White))
        Ticks()
        strip.show()
        strip.setPixelColor(12, neopixel.colors(NeoPixelColors.Black))
        strip.setPixelColor(14, neopixel.colors(NeoPixelColors.Blue))
        strip.setPixelColor(15, neopixel.colors(NeoPixelColors.White))
        Ticks()
        strip.show()
        strip.setPixelColor(13, neopixel.colors(NeoPixelColors.Black))
        strip.setPixelColor(15, neopixel.colors(NeoPixelColors.Blue))
        strip.setPixelColor(16, neopixel.colors(NeoPixelColors.White))
        Ticks()
        strip.show()
        strip.setPixelColor(14, neopixel.colors(NeoPixelColors.Black))
        strip.setPixelColor(16, neopixel.colors(NeoPixelColors.Blue))
        strip.setPixelColor(17, neopixel.colors(NeoPixelColors.White))
        Ticks()
        strip.show()
        strip.setPixelColor(15, neopixel.colors(NeoPixelColors.Black))
        strip.setPixelColor(17, neopixel.colors(NeoPixelColors.Blue))
        strip.setPixelColor(18, neopixel.colors(NeoPixelColors.White))
        Ticks()
        strip.show()
        strip.setPixelColor(16, neopixel.colors(NeoPixelColors.Black))
        strip.setPixelColor(18, neopixel.colors(NeoPixelColors.Blue))
        strip.setPixelColor(19, neopixel.colors(NeoPixelColors.White))
        Ticks()
        strip.show()
        strip.setPixelColor(17, neopixel.colors(NeoPixelColors.Black))
        strip.setPixelColor(19, neopixel.colors(NeoPixelColors.Blue))
        strip.setPixelColor(20, neopixel.colors(NeoPixelColors.White))
        Ticks()
        strip.show()
        strip.setPixelColor(18, neopixel.colors(NeoPixelColors.Black))
        strip.setPixelColor(20, neopixel.colors(NeoPixelColors.Blue))
        strip.setPixelColor(21, neopixel.colors(NeoPixelColors.White))
        Ticks()
        strip.show()
        strip.setPixelColor(19, neopixel.colors(NeoPixelColors.Black))
        strip.setPixelColor(21, neopixel.colors(NeoPixelColors.Blue))
        strip.setPixelColor(22, neopixel.colors(NeoPixelColors.White))
        Ticks()
        strip.show()
        strip.setPixelColor(20, neopixel.colors(NeoPixelColors.Black))
        strip.setPixelColor(22, neopixel.colors(NeoPixelColors.Blue))
        strip.setPixelColor(23, neopixel.colors(NeoPixelColors.White))
        Ticks()
        strip.show()
        strip.setPixelColor(21, neopixel.colors(NeoPixelColors.Black))
        strip.setPixelColor(23, neopixel.colors(NeoPixelColors.Blue))
        strip.setPixelColor(24, neopixel.colors(NeoPixelColors.White))
        Ticks()
        strip.show()
        strip.setPixelColor(22, neopixel.colors(NeoPixelColors.Black))
        strip.setPixelColor(24, neopixel.colors(NeoPixelColors.Blue))
        strip.setPixelColor(25, neopixel.colors(NeoPixelColors.White))
        Ticks()
        strip.show()
        strip.setPixelColor(23, neopixel.colors(NeoPixelColors.Black))
        strip.setPixelColor(25, neopixel.colors(NeoPixelColors.Blue))
        strip.setPixelColor(26, neopixel.colors(NeoPixelColors.White))
        Ticks()
        strip.show()
        strip.setPixelColor(24, neopixel.colors(NeoPixelColors.Black))
        strip.setPixelColor(26, neopixel.colors(NeoPixelColors.Blue))
        strip.setPixelColor(27, neopixel.colors(NeoPixelColors.White))
        Ticks()
        strip.show()
        strip.setPixelColor(25, neopixel.colors(NeoPixelColors.Black))
        strip.setPixelColor(27, neopixel.colors(NeoPixelColors.Blue))
        strip.setPixelColor(28, neopixel.colors(NeoPixelColors.White))
        Ticks()
        strip.show()
        strip.setPixelColor(26, neopixel.colors(NeoPixelColors.Black))
        strip.setPixelColor(28, neopixel.colors(NeoPixelColors.Blue))
        strip.setPixelColor(29, neopixel.colors(NeoPixelColors.White))
        Ticks()
        strip.show()
        strip.setPixelColor(27, neopixel.colors(NeoPixelColors.Black))
        strip.setPixelColor(29, neopixel.colors(NeoPixelColors.Blue))
        strip.setPixelColor(30, neopixel.colors(NeoPixelColors.White))
        Ticks()
        strip.show()
        strip.setPixelColor(28, neopixel.colors(NeoPixelColors.Black))
        strip.setPixelColor(30, neopixel.colors(NeoPixelColors.White))
        strip.setPixelColor(30, neopixel.colors(NeoPixelColors.White))
        Ticks()
        strip.show()
        strip.setPixelColor(29, neopixel.colors(NeoPixelColors.Black))
        strip.setPixelColor(30, neopixel.colors(NeoPixelColors.White))
        Ticks()
        strip.show()
        strip.setPixelColor(30, neopixel.colors(NeoPixelColors.Black))
        strip.setPixelColor(30, neopixel.colors(NeoPixelColors.White))
    }
})
basic.forever(function () {
    for (let index = 0; index < 1e+101; index++) {
        Strip2.show()
        Strip2.setPixelColor(0, neopixel.colors(NeoPixelColors.Blue))
        Strip2.setPixelColor(1, neopixel.colors(NeoPixelColors.Blue))
        Strip2.setPixelColor(2, neopixel.colors(NeoPixelColors.White))
        Ticks()
        Strip2.show()
        Strip2.setPixelColor(0, neopixel.colors(NeoPixelColors.Black))
        Strip2.setPixelColor(2, neopixel.colors(NeoPixelColors.Blue))
        Strip2.setPixelColor(3, neopixel.colors(NeoPixelColors.White))
        Ticks()
        Strip2.show()
        Strip2.setPixelColor(1, neopixel.colors(NeoPixelColors.Black))
        Strip2.setPixelColor(3, neopixel.colors(NeoPixelColors.Blue))
        Strip2.setPixelColor(4, neopixel.colors(NeoPixelColors.White))
        Ticks()
        Strip2.show()
        Strip2.setPixelColor(2, neopixel.colors(NeoPixelColors.Black))
        Strip2.setPixelColor(4, neopixel.colors(NeoPixelColors.Blue))
        Strip2.setPixelColor(5, neopixel.colors(NeoPixelColors.White))
        Ticks()
        Strip2.show()
        Strip2.setPixelColor(3, neopixel.colors(NeoPixelColors.Black))
        Strip2.setPixelColor(5, neopixel.colors(NeoPixelColors.Blue))
        Strip2.setPixelColor(6, neopixel.colors(NeoPixelColors.White))
        Ticks()
        Strip2.show()
        Strip2.setPixelColor(4, neopixel.colors(NeoPixelColors.Black))
        Strip2.setPixelColor(6, neopixel.colors(NeoPixelColors.Blue))
        Strip2.setPixelColor(7, neopixel.colors(NeoPixelColors.White))
        Ticks()
        Strip2.show()
        Strip2.setPixelColor(5, neopixel.colors(NeoPixelColors.Black))
        Strip2.setPixelColor(7, neopixel.colors(NeoPixelColors.Blue))
        Strip2.setPixelColor(8, neopixel.colors(NeoPixelColors.White))
        Ticks()
        Strip2.show()
        Strip2.setPixelColor(6, neopixel.colors(NeoPixelColors.Black))
        Strip2.setPixelColor(8, neopixel.colors(NeoPixelColors.Blue))
        Strip2.setPixelColor(9, neopixel.colors(NeoPixelColors.White))
        Ticks()
        Strip2.show()
        Strip2.setPixelColor(7, neopixel.colors(NeoPixelColors.Black))
        Strip2.setPixelColor(9, neopixel.colors(NeoPixelColors.Blue))
        Strip2.setPixelColor(10, neopixel.colors(NeoPixelColors.White))
        Ticks()
        Strip2.show()
        Strip2.setPixelColor(8, neopixel.colors(NeoPixelColors.Black))
        Strip2.setPixelColor(10, neopixel.colors(NeoPixelColors.Blue))
        Strip2.setPixelColor(11, neopixel.colors(NeoPixelColors.White))
        Ticks()
        Strip2.show()
        Strip2.setPixelColor(9, neopixel.colors(NeoPixelColors.Black))
        Strip2.setPixelColor(11, neopixel.colors(NeoPixelColors.Blue))
        Strip2.setPixelColor(12, neopixel.colors(NeoPixelColors.White))
        Ticks()
        Strip2.show()
        Strip2.setPixelColor(10, neopixel.colors(NeoPixelColors.Black))
        Strip2.setPixelColor(12, neopixel.colors(NeoPixelColors.Blue))
        Strip2.setPixelColor(13, neopixel.colors(NeoPixelColors.White))
        Ticks()
        Strip2.show()
        Strip2.setPixelColor(11, neopixel.colors(NeoPixelColors.Black))
        Strip2.setPixelColor(13, neopixel.colors(NeoPixelColors.Blue))
        Strip2.setPixelColor(14, neopixel.colors(NeoPixelColors.White))
        Ticks()
        Strip2.show()
        Strip2.setPixelColor(12, neopixel.colors(NeoPixelColors.Black))
        Strip2.setPixelColor(14, neopixel.colors(NeoPixelColors.Blue))
        Strip2.setPixelColor(15, neopixel.colors(NeoPixelColors.White))
        Ticks()
        Strip2.show()
        Strip2.setPixelColor(13, neopixel.colors(NeoPixelColors.Black))
        Strip2.setPixelColor(15, neopixel.colors(NeoPixelColors.Blue))
        Strip2.setPixelColor(16, neopixel.colors(NeoPixelColors.White))
        Ticks()
        Strip2.show()
        Strip2.setPixelColor(14, neopixel.colors(NeoPixelColors.Black))
        Strip2.setPixelColor(16, neopixel.colors(NeoPixelColors.Blue))
        Strip2.setPixelColor(17, neopixel.colors(NeoPixelColors.White))
        Ticks()
        Strip2.show()
        Strip2.setPixelColor(15, neopixel.colors(NeoPixelColors.Black))
        Strip2.setPixelColor(17, neopixel.colors(NeoPixelColors.Blue))
        Strip2.setPixelColor(18, neopixel.colors(NeoPixelColors.White))
        Ticks()
        Strip2.show()
        Strip2.setPixelColor(16, neopixel.colors(NeoPixelColors.Black))
        Strip2.setPixelColor(18, neopixel.colors(NeoPixelColors.Blue))
        Strip2.setPixelColor(19, neopixel.colors(NeoPixelColors.White))
        Ticks()
        Strip2.show()
        Strip2.setPixelColor(17, neopixel.colors(NeoPixelColors.Black))
        Strip2.setPixelColor(19, neopixel.colors(NeoPixelColors.Blue))
        Strip2.setPixelColor(20, neopixel.colors(NeoPixelColors.White))
        Ticks()
        Strip2.show()
        Strip2.setPixelColor(18, neopixel.colors(NeoPixelColors.Black))
        Strip2.setPixelColor(20, neopixel.colors(NeoPixelColors.Blue))
        Strip2.setPixelColor(21, neopixel.colors(NeoPixelColors.White))
        Ticks()
        Strip2.show()
        Strip2.setPixelColor(19, neopixel.colors(NeoPixelColors.Black))
        Strip2.setPixelColor(21, neopixel.colors(NeoPixelColors.Blue))
        Strip2.setPixelColor(22, neopixel.colors(NeoPixelColors.White))
        Ticks()
        Strip2.show()
        Strip2.setPixelColor(20, neopixel.colors(NeoPixelColors.Black))
        Strip2.setPixelColor(22, neopixel.colors(NeoPixelColors.Blue))
        Strip2.setPixelColor(23, neopixel.colors(NeoPixelColors.White))
        Ticks()
        Strip2.show()
        Strip2.setPixelColor(21, neopixel.colors(NeoPixelColors.Black))
        Strip2.setPixelColor(23, neopixel.colors(NeoPixelColors.Blue))
        Strip2.setPixelColor(24, neopixel.colors(NeoPixelColors.White))
        Ticks()
        Strip2.show()
        Strip2.setPixelColor(22, neopixel.colors(NeoPixelColors.Black))
        Strip2.setPixelColor(24, neopixel.colors(NeoPixelColors.Blue))
        Strip2.setPixelColor(25, neopixel.colors(NeoPixelColors.White))
        Ticks()
        Strip2.show()
        Strip2.setPixelColor(23, neopixel.colors(NeoPixelColors.Black))
        Strip2.setPixelColor(25, neopixel.colors(NeoPixelColors.Blue))
        Strip2.setPixelColor(26, neopixel.colors(NeoPixelColors.White))
        Ticks()
        Strip2.show()
        Strip2.setPixelColor(24, neopixel.colors(NeoPixelColors.Black))
        Strip2.setPixelColor(26, neopixel.colors(NeoPixelColors.Blue))
        Strip2.setPixelColor(27, neopixel.colors(NeoPixelColors.White))
        Ticks()
        Strip2.show()
        Strip2.setPixelColor(25, neopixel.colors(NeoPixelColors.Black))
        Strip2.setPixelColor(27, neopixel.colors(NeoPixelColors.Blue))
        Strip2.setPixelColor(28, neopixel.colors(NeoPixelColors.White))
        Ticks()
        Strip2.show()
        Strip2.setPixelColor(26, neopixel.colors(NeoPixelColors.Black))
        Strip2.setPixelColor(28, neopixel.colors(NeoPixelColors.Blue))
        Strip2.setPixelColor(29, neopixel.colors(NeoPixelColors.White))
        Ticks()
        Strip2.show()
        Strip2.setPixelColor(27, neopixel.colors(NeoPixelColors.Black))
        Strip2.setPixelColor(29, neopixel.colors(NeoPixelColors.Blue))
        Strip2.setPixelColor(30, neopixel.colors(NeoPixelColors.White))
        Ticks()
        Strip2.show()
        Strip2.setPixelColor(28, neopixel.colors(NeoPixelColors.Black))
        Strip2.setPixelColor(30, neopixel.colors(NeoPixelColors.White))
        Strip2.setPixelColor(30, neopixel.colors(NeoPixelColors.White))
        Ticks()
        Strip2.show()
        Strip2.setPixelColor(29, neopixel.colors(NeoPixelColors.Black))
        Strip2.setPixelColor(30, neopixel.colors(NeoPixelColors.White))
        Ticks()
        Strip2.show()
        Strip2.setPixelColor(30, neopixel.colors(NeoPixelColors.Black))
        Strip2.setPixelColor(30, neopixel.colors(NeoPixelColors.White))
    }
})
